protected/controllers/SiteController.php
<?php

class SiteController extends Controller
{
	public $layout='/layouts/site';
	public $siteMenu = array();
	public $contentMenu = array();
	public $lang = 'en';

	/********************************************************************************************
	 *	Actions for SiteController
	 ********************************************************************************************/

	/**
	 * Declares class-based actions.
	 */
	public function actions()
	{
		return array(
			// captcha action renders the CAPTCHA image displayed on the contact page
			'captcha'=>array(
				'class'=>'CCaptchaAction',
				'backColor'=>0xFFFFFF,
			),
			// page action renders "static" pages stored under 'protected/views/site/pages'
			// They can be accessed via: index.php?r=site/page&view=FileName
			//'page'=>array(
			//	'class'=>'CViewAction',
			//),
		);
	}

	/**
	 * This is the default 'index' action that is invoked
	 * when an action is not explicitly requested by users.
	 */
	public function actionIndex()
	{
		//Yii::app()->session['lang'] = 'en';
		//echo Yii::app()->session['lang']; // Prints "value"
		$mainArticles = $this->fetchMainArticle(Yii::app()->language);
		$interestingArticles = $this->fetchInterestingArticles(Yii::app()->language);
		$albums = $this->fetchMainCarousal(Yii::app()->language);
		$this->render('index', array('interestingArticles' => $interestingArticles, 'album' => $albums[0], 'mainArticles' => $mainArticles ));
	}

	public function actionNews()
	{
		//Yii::app()->session['lang'] = 'en';
		//echo Yii::app()->session['lang']; // Prints "value"
		$newsArticles = $this->fetchNewsArticles(Yii::app()->language);
		$this->render('news', array('newsArticles' => $newsArticles));
	}

	public function actionPage($view = '')
	{

		if ( $view != '' )
		{
			if($this->getViewFile('pages/'.$this->lang.'/'.$view)!==false)
			{
				$this->render('pages/'.$this->lang.'/'.$view);
				return;
			}
			else if($this->getViewFile('pages/'.$view)!==false)
			{
				$this->render('pages/'.$view);
				return;
			}
		}

		$this->render('index');

	}

	public function actionGallery()
	{

		$albums = $this->fetchGalleryAlbums(Yii::app()->language);

		$this->render('gallery', array('albums'=>$albums));
	}

	public function actionArticle($id=0)
	{

		$model = null;
		if ( $id != 0 )
		{
			$model = Article::model()->findByPk($id);

		}

		if ( $model == null )
		{
			$this->redirect(Yii::app()->homeUrl);
		}
		else
		{
			$this->render('article', array('model'=>$model));
		}
	}

	public function actionAdmin()
	{
		// renders the view file 'protected/views/site/index.php'
		// using the default layout 'protected/views/layouts/main.php'
		$this->layout='/layouts/main';
		$this->render('admin');
	}

	/**
	 * This is the action to handle external exceptions.
	 */
	public function actionError()
	{
		if (isset(Yii::app()->session['lang']))
		{
			$this->lang = Yii::app()->session['lang'];
		}
		Yii::app()->language = $this->lang;

		if($error=Yii::app()->errorHandler->error)
		{
			if(Yii::app()->request->isAjaxRequest)
				echo $error['message'];
			else
				$this->render('error', $error);
		}
	}

	/**
	 * Displays the contact page
	 */
	public function actionContact()
	{

		$model=new ContactForm;
		if(isset($_POST['ContactForm']))
		{
			$model->attributes=$_POST['ContactForm'];
			if($model->validate())
			{
				$name='=?UTF-8?B?'.base64_encode($model->name).'?=';
				$subject='=?UTF-8?B?'.base64_encode($model->subject).'?=';
				$headers="From: $name <{$model->email}>\r\n".
					"Reply-To: {$model->email}\r\n".
					"MIME-Version: 1.0\r\n".
					"Content-type: text/plain; charset=UTF-8";

				mail(Yii::app()->params['adminEmail'],$subject,$model->body,$headers);
				Yii::app()->user->setFlash('contact','Thank you for contacting us. We will respond to you as soon as possible.');
				$this->refresh();
			}
		}
		$this->render('contact',array('model'=>$model));
	}

	/**
	 * Displays the login page
	 */
	public function actionLogin()
	{
		$this->layout='/layouts/main';
		$model=new LoginForm;

		// if it is ajax validation request
		if(isset($_POST['ajax']) && $_POST['ajax']==='login-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}

		// collect user input data
		if(isset($_POST['LoginForm']))
		{
			$model->attributes=$_POST['LoginForm'];
			// validate user input and redirect to the previous page if valid
			if($model->validate() && $model->login())
				$this->redirect(Yii::app()->user->returnUrl);
		}
		// display the login form
		$this->render('login',array('model'=>$model));
	}

	/**
	 * Logs out the current user and redirect to homepage.
	 */
	public function actionLogout()
	{
		$this->layout='/layouts/main';
		Yii::app()->user->logout();
		$this->redirect(Yii::app()->homeUrl);
	}

	public function actionLanguage($lang='en')
	{
		Yii::app()->session['lang'] = $lang;
		$this->redirect(Yii::app()->user->returnUrl);
	}

	/********************************************************************************************
	 *	End of Actions for SiteController
	 ********************************************************************************************/

	/********************************************************************************************
	 *	Filters for SiteController
	 ********************************************************************************************/

	public function filters()
    {
        return array(
			'selectLang - language',
            'loadMenu + index, article, error, page, contact, news, gallery - language'
        );
    }

	public function filterSelectLang($filterChain)
	{
		if (isset(Yii::app()->session['lang']))
		{
			$this->lang = Yii::app()->session['lang'];
		}
		Yii::app()->language = $this->lang;
		//echo Yii::app()->language;
		$filterChain->run();
	}

	public function filterLoadMenu($filterChain)
	{
		$this->siteMenu = $this->fetchMenu('SITE', Yii::app()->language);
		$this->contentMenu = $this->fetchMenu('CONTENT', Yii::app()->language);

		$filterChain->run();
	}

	/********************************************************************************************
	 *	Filters for SiteController
	 ********************************************************************************************/

	/********************************************************************************************
	 *	Private helper functions for SiteController
	 ********************************************************************************************/

	private function fetchMainArticle($lang)
	{
		$article = Article::model()->findAllBySql('select a.header_'.$lang.', a.content_'.$lang.'
												from article a 
												inner join article_category ac on a.article_category_id = ac.id 
												where ac.category_cd = "ADHOC" and a.sort_order = 1;');

		return $article;
	}

	private function fetchGalleryAlbums($lang)
	{
		$albums = Album::model()->findAllBySql('select id, album_cd, header_'.$lang.', desc_'.$lang.'
												from album where gallery = 1
												order by sort_order;');

		return $this->fetchAlbumImages($albums, $lang);
	}

	private function fetchMainCarousal($lang)
	{
		$albums = Album::model()->findAllBySql('select id, album_cd, header_'.$lang.', desc_'.$lang.'
												from album where album_cd = "MAINCAROUSAL"
												order by sort_order;');

		return $this->fetchAlbumImages($albums, $lang);
	}

	private function fetchAlbumImages($albums, $lang)
	{
		$returnAlbums = array();

		foreach($albums as $album) {

			$images = Image::model()->findAllBySql('	select id, image_cd, desc_'.$lang.', link, height, width 
														from image 
														where album_id = '.$album['id'].'
														order by sort_order;');

			if ( count($images) > 0 )
			{
				$imageList = array();
				foreach($images as $image) {

					$imageList[] = array(	'img' => $image['link'], 
											'desc' => $image['desc_'.$lang], 
											'height' => $image['height'], 
											'width' => $image['width']);
				}

				$returnAlbums[] = array(	'id' => $album['album_cd'], 
											'header' => $album['header_'.$lang], 
											'desc' => $album['desc_'.$lang], 
											'images' => $imageList);
			}

		}
		return $returnAlbums;

	}

	private function fetchInterestingArticles($lang)
	{
		$returnArticles = array();
		$articles = Article::model()->findAllBySql(	'select id, header_'.$lang.', content_'.$lang.'
													from article where interest > 0 
													order by id desc;');
		foreach($articles as $article) {
			// strip <h> tags from content
			$content = $article['content_'.$lang];
			$content = preg_replace('$<h[1-9]>$', '<b>', $content);
			$content = preg_replace('$</h[1-9]>$', '</b>', $content);


			$returnArticles[] = array(	'header' => $article['header_'.$lang], 
										'content' => $content,
										'link' => 'index.php?r=/site/article&id='.$article['id']);

		}
		return $returnArticles;
	}

	private function fetchNewsArticles($lang)
	{
		$returnArticles = array();
		$articles = Article::model()->findAllBySql(	'select id, header_'.$lang.', content_'.$lang.'
													from article where article_category_id = (select id from article_category where category_cd = \'NEWS\') 
													order by id desc;');
		foreach($articles as $article) {
			// strip <h> tags from content
			$content = $article['content_'.$lang];
			$content = preg_replace('$<h[1-9]>$', '<b>', $content);
			$content = preg_replace('$</h[1-9]>$', '</b>', $content);


			$returnArticles[] = array(	'header' => $article['header_'.$lang], 
										'content' => $content,
										'link' => 'index.php?r=/site/article&id='.$article['id']);

		}

protected/views/layouts/_footer.php
    <div class="page">
        <div class="nav-bar bg-color-greenLight">
            <div class="nav-bar-inner padding10">
                <span class="element left">
                    <?php echo Yii::t('strings', 'COPYRIGHT'); ?>
					<a class="fg-color-white" href="mailto:watpo.ttm@gmail.com"><?php echo CHtml::encode(Yii::t('strings',Yii::app()->name)); ?></a>.
                </span>
				<span class="element right">
					<?php echo Yii::t('strings', 'METROUI'); ?> <a class="fg-color-white" href="http://metroui.org.ua">Metro UI CSS</a> | <?php echo Yii::powered(); ?>
				</span>
            </div>
        </div>
    </div>

protected/views/layouts/_header.php
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="target-densitydpi=device-dpi, width=device-width, initial-scale=1.0, maximum-scale=1">
    <meta name="author" content="WatpoTTM">
	<meta name="keywords" content="Thai Massage,Massage Course,Massage Knowledge,Massage School,Thai Massage Course,Thai Massage Knowledge,Thai Massage School,Spa,Therapy,Therapist,Medical Massage">
	<meta name="description" content="Thai Massage,Massage Course,Massage Knowledge,Massage School,Thai Massage Course,Thai Massage Knowledge,Thai Massage School">
    <link href="<?php echo Yii::app()->request->baseUrl; ?>/css/modern.css" rel="stylesheet">
    <link href="<?php echo Yii::app()->request->baseUrl; ?>/css/modern-responsive.css" rel="stylesheet">
    <link href="<?php echo Yii::app()->request->baseUrl; ?>/css/site.css" rel="stylesheet" type="text/css">
	<link href="<?php echo Yii::app()->request->baseUrl; ?>/css/form.css" rel="stylesheet" type="text/css">

    <script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl; ?>/js/assets/jquery-1.9.0.min.js"></script>
    <script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl; ?>/js/assets/jquery.mousewheel.min.js"></script>
    <script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl; ?>/js/assets/moment.js"></script>
    <script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl; ?>/js/assets/moment_langs.js"></script>

    <script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl; ?>/js/modern/dropdown.js"></script>
    <script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl; ?>/js/modern/accordion.js"></script>
    <script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl; ?>/js/modern/buttonset.js"></script>
    <script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl; ?>/js/modern/carousel.js"></script>
    <script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl; ?>/js/modern/input-control.js"></script>
    <script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl; ?>/js/modern/pagecontrol.js"></script>
    <script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl; ?>/js/modern/rating.js"></script>
    <script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl; ?>/js/modern/slider.js"></script>
    <script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl; ?>/js/modern/tile-slider.js"></script>
    <script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl; ?>/js/modern/tile-drag.js"></script>
    <script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl; ?>/js/modern/calendar.js"></script>

	<title><?php echo CHtml::encode($this->pageTitle); ?></title>
</head>

protected/views/layouts/_navigation.php
<div class="page">
	<div class="nav-bar bg-color-greenDark">

		<div class="nav-bar-inner padding10">
			<span class="pull-menu"></span>

			<a href="index.php">
				<span class="element brand">
					<img class="place-left logoimage" src="images/logo32.png" />
					<?php echo Yii::t('strings',Yii::app()->name); ?>
				</span>
			</a>

			<?php $this->widget('application.components.UIMenu', array(
				  'menu' => $this->siteMenu,
				  'position' => 'right'
				)); ?>

			<div class="divider"></div>

		</div>

		<div class="nav-bar-inner padding10">
			<span class="pull-menu"></span>

			<?php $this->widget('application.components.UIMenu', array(
				  'menu' => $this->contentMenu,
				  'position' => 'right'
				)); ?>

			<div class="divider"></div>

		</div>
	</div>
</div>

protected/views/layouts/column1.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div id="content">
	<?php echo $content; ?>
</div><!-- content -->
<?php $this->endContent(); ?>

protected/views/layouts/column2.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div class="span-19">
	<div id="content">
		<?php echo $content; ?>
	</div><!-- content -->
</div>
<div class="span-5 last">
	<div id="sidebar">
	<?php
		$this->beginWidget('zii.widgets.CPortlet', array(
			'title'=>'Operations',
		));
		$this->widget('zii.widgets.CMenu', array(
			'items'=>$this->menu,
			'htmlOptions'=>array('class'=>'operations'),
		));
		$this->endWidget();
	?>
	</div><!-- sidebar -->
</div>
<?php $this->endContent(); ?>

protected/views/layouts/main.php
<?php /* @var $this Controller */ ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="language" content="en" />

	<!-- blueprint CSS framework -->
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/screen.css" media="screen, projection" />
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/print.css" media="print" />
	<!--[if lt IE 8]>
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/ie.css" media="screen, projection" />
	<![endif]-->

	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/main.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/form.css" />

	<title><?php echo CHtml::encode($this->pageTitle); ?></title>
</head>

<body>

<div class="container" id="page">

	<div id="header">
		<div id="logo"><?php echo CHtml::encode(Yii::t('strings',Yii::app()->name)); ?></div>
	</div><!-- header -->

	<div id="mainmenu">
		<?php $this->widget('zii.widgets.CMenu',array(
			'items'=>array(
				array('label'=>'Site Home', 'url'=>array('/site/index')),
				array('label'=>'Admin Home', 'url'=>array('/site/admin')),
				array('label'=>'Login', 'url'=>array('/site/login'), 'visible'=>Yii::app()->user->isGuest),
				array('label'=>'Article Category', 'url'=>array('/articleCategory'), 'visible'=>!Yii::app()->user->isGuest),
				array('label'=>'Article', 'url'=>array('/article'), 'visible'=>!Yii::app()->user->isGuest),
				array('label'=>'Menu', 'url'=>array('/menu'), 'visible'=>!Yii::app()->user->isGuest),
				array('label'=>'Album', 'url'=>array('/album'), 'visible'=>!Yii::app()->user->isGuest),
				array('label'=>'Image', 'url'=>array('/image'), 'visible'=>!Yii::app()->user->isGuest),
				array('label'=>'Logout ('.Yii::app()->user->name.')', 'url'=>array('/site/logout'), 'visible'=>!Yii::app()->user->isGuest)
			),
		)); ?>
	</div><!-- mainmenu -->
	<?php if(isset($this->breadcrumbs)):?>
		<?php $this->widget('zii.widgets.CBreadcrumbs', array(
			'links'=>$this->breadcrumbs,
		)); ?><!-- breadcrumbs -->
	<?php endif?>

	<?php echo $content; ?>

	<div class="clear"></div>

	<div id="footer">
		Copyright &copy; <?php echo date('Y'); ?> by My Company.<br/>
		All Rights Reserved.<br/>
		<?php echo Yii::powered(); ?>
	</div><!-- footer -->

</div><!-- page -->

</body>
</html>

protected/views/layouts/site.php
<?php /* @var $this Controller */ ?>

	<?php $this->renderPartial('/layouts/_header') ?>

	<body class="metrouicss <?php echo Yii::t('strings', 'LANGUAGE'); ?>" >

	<?php $this->renderPartial('/layouts/_navigation') ?>

	<?php echo $content; ?>

	<?php $this->renderPartial('/layouts/_footer') ?>

    </body>
</html>